export enum Actions {
  ADD_STAGE = "ADD_STAGE",
  REMOVE_STAGE = "REMOVE_STAGE",
  EDIT_STAGE = "EDIT_STAGE",
  ADD_STEP = "ADD_STEP",
  REMOVE_STEP = "REMOVE_STEP",
  TOGGLE_STEP = "TOGGLE_STEP",
}
